### ISSUE TITLE
Missing Word

### ISSUE THREAD

**Issue by darrendc** [learn-co-curriculum/phrg-sinatra-nested-forms-readme#2]
Under the "Forms That Create Multiple Objects" heading, in the first sentence of the third paragraph, the word "in" is missing.  "Let's say we're [in] the registrar's office at a school..."

**Comment by garettarrowood** [comment]
Resolved in this commit - https://github.com/learn-co-curriculum/phrg-sinatra-nested-forms-readme/commit/51f6e2c99c7e5b3d980f05f739b90e6f56208abf
